#8004表示注册到zookeeper服务器的支付服务提供者端口号
server:
  port: 80
#别名----注册zookeeper到注册中心名称
spring:
  application:
    name: cloud-consumer-service
  cloud:
    zookeeper:
      connect-string: 192.168.111.144:2181

